[package]
name = "lesson_6_1_simple"
version = "0.1.0"
authors = ["Lucas Lemos <stiltztinkerstein@gmail.com>"]
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"

